"use client";
import type { SongPreviewLayer } from "@/components/song-preview-player";
import type { PlanEditorTask } from "@/components/plan-editor";
import type { Task, ProjectMeta, Screen, Phase } from "@/lib/studio/session-types";
import type { PlanMode } from "@/lib/plan";
import type React from "react";

export type SessionBoothViewProps = {
  id: string;
  C: Record<string, string>;
  project: ProjectMeta | null;
  beatUrl: string | null;
  tasks: Task[];
  planTasks: PlanEditorTask[];
  screen: Screen;
  phase: Phase;
  loading: boolean;
  analyzing: boolean;
  error: string | null;
  producerTip: string | null;
  producing: boolean;
  produceStage: string | null;
  masterUrl: string | null;
  countdown: number;
  localBlobUrl: string | null;
  reviewVoiceOnly: boolean;
  uploading: boolean;
  savedRecordingId: string | null;
  skipping: boolean;
  planMode: PlanMode;
  recordSeconds: number;
  current: Task | null;
  isRetake: boolean;
  sectionMs: number | null;
  micStream: MediaStream | null;
  selectedMicId: string;
  selectedSpeakerId: string;
  previewLayers: SongPreviewLayer[];
  previewBeatUrl: string | null;
  previewBeatDurationMs: number | null;
  previewLoading: boolean;
  lastRecordingOffsetMs: number;
  beatAudioRef: React.RefObject<HTMLAudioElement | null>;
  uploadInputRef: React.RefObject<HTMLInputElement | null>;
  setScreen: (s: Screen) => void;
  setPlanMode: (m: PlanMode) => void;
  setPlanTasks: (t: PlanEditorTask[]) => void;
  setTasks: React.Dispatch<React.SetStateAction<Task[]>>;
  setSelectedMicId: (id: string) => void;
  setSelectedSpeakerId: (id: string) => void;
  setReviewVoiceOnly: React.Dispatch<React.SetStateAction<boolean>>;
  setLocalBlobUrl: (u: string | null) => void;
  setSavedRecordingId: (id: string | null) => void;
  setProducerTip: (t: string | null) => void;
  setPhase: (p: Phase) => void;
  selectTask: (id: string) => void;
  startProducerSession: () => void;
  generateAiPlan: (mode?: PlanMode) => void;
  enterSession: () => void;
  startRecording: () => void;
  cancelCountdown: () => void;
  stopRecording: () => void;
  keepAndContinue: () => void;
  skipCurrent: () => void;
  skipAllOptional: () => void;
  startProduce: () => void;
  loadSongPreview: () => void;
  uploadForTask: (f: File | null) => void;
};
